
SELECT * FROM tb_clientes;

SELECT * FROM tb_clientes WHERE DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM tb_clientes WHERE DATA_NASCIMENTO > '1995-01-13';

SELECT * FROM tb_clientes WHERE DATA_NASCIMENTO <= '1995-01-13';

SELECT * FROM tb_clientes WHERE YEAR(DATA_NASCIMENTO) = 1995;

SELECT * FROM tb_clientes WHERE MONTH(DATA_NASCIMENTO) = 10;