
SELECT * FROM tb_clientes;

ALTER TABLE tb_clientes ADD COLUMN (DATA_NASCIMENTO DATE);

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP,
DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM tb_clientes;

SELECT CPF, NOME FROM tb_clientes;

SELECT CPF, NOME FROM tb_clientes LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tb_clientes;

SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM tb_clientes;

