CREATE DATABASE vendas_sucos;

CREATE DATABASE vendas_sucos2 DEFAULT CHARACTER SET utf8;

CREATE DATABASE IF NOT exists vendas_sucos2;

DROP DATABASE IF EXISTS vendas_sucos2;

USE vendas_sucos;

CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA));

ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

CREATE TABLE `vendas_sucos`.`notas` (
  `numero` VARCHAR(5) NOT NULL,
  `data_venda` DATE NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `matricula` VARCHAR(5) NOT NULL,
  `imposto` FLOAT NULL,
  PRIMARY KEY (`numero`));
  
  CREATE TABLE `vendas_sucos`.`itens_notas` (
  `numero` VARCHAR(5) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `quantidade` INT(11) NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`numero`, `codigo`));
  
CREATE TABLE `vendas_sucos`.`clientes` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(150) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(50) NULL,
  `cep` VARCHAR(8) NULL,
  `data_nascimento` DATE NULL,
  `idade` INT NULL,
  `sexo` VARCHAR(1) NULL,
  `limite_credito` FLOAT NULL,
  `volume_compra` FLOAT NULL,
  `primeira_compra` TINYINT NULL,
  PRIMARY KEY (`cpf`));
  
CREATE TABLE tabela_de_vendas
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

ALTER TABLE tabela_de_vendas ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

ALTER TABLE tabela_de_vendas RENAME Notas;